version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: ${IMAGE_NAME}:latest
    container_name: ${CONTAINER_NAME}-Server
    volumes:
      - ./cache:/app/cache
      - ./dict:/app/dict
      - ./.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - tunnel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: ${CONTAINER_NAME}-Redis
    image: redis:latest
    volumes:
      - /data/docker-service/redis_cache/${IMAGE_NAME}:/data
    restart: unless-stopped

  tunnel:
    container_name: ${CONTAINER_NAME}-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
