#!/bin/sh
# Build Stage
FROM python:3.11-alpine3.18 AS builder
WORKDIR /code
ADD . /code
RUN apk add --no-cache gcc g++ musl-dev rust cargo patchelf
RUN pip install "fastapi[standard]"
RUN pip install redis
RUN pip install sqlalchemy
RUN pip install pymysql
RUN pip install pyinstaller
RUN pyinstaller -F main.py

# Runtime
FROM alpine:3.18 AS runtime
WORKDIR /app
COPY --from=builder /code/dist/main .
EXPOSE 8000
ENTRYPOINT ["./main"]